version: "3"

services:
  db:
    image: mysql:8.0.23
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --skip-character-set-client-handshake --default-authentication-plugin=mysql_native_password
    container_name: ls-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
      args:
        ENV_FILE: docker-local.env
    container_name: bs-client
    env_file:
      - next/.env
      - next/docker-local.env
    ports:
      - "5200:8080"
    depends_on:
      - ws

  ws:
    build:
      context: .
      dockerfile: ./docker/ws/Dockerfile
      args:
        ENV_FILE: docker-local.env
    container_name: bs-ws
    env_file:
      - NetCoreGameServer/.env
      - NetCoreGameServer/docker-local.env
    ports:
      - "5201:4000"
