version: "3"

services:
  db:
    image: mysql:8.0.23
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --skip-character-set-client-handshake --default-authentication-plugin=mysql_native_password
    container_name: ls-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
