import Character from "./Character";
import Item, { getItemType, ItemType } from "./Item";

export enum CharacterStats {
  EnhancedEffect,
  Strength,
  Dexterity,
  Vitality,
  Intelligence,
  MaxLife,
  MaxMana,
  ExperienceGained,
  MagicLuck,
  LifeRegen,
  ManaRegen,
  ExtraEquipmentSlots,
  CriticalStrike,
  LifePerAttack,
  ManaPerAttack,
  LifePerKill,
  ManaPerKill,
  LifeSteal,
  DamageReturn,
  MindNumb,
  ArmorPierce,
  Parry,
  CriticalFlux,
  PhysicalDamageReduction,
  MagicalDamageReduction,
  ManaSyphon,
  QuickDraw,
  ManaConsumption,
  IceMastery,
  FireMastery,
  LightningMastery,
  EarthMastery,
  WindMastery,
  HealMastery,
  ManaSkin,
  PowerShot,
  GlancingBlow,
  Jubilance,
}


export enum ItemStats {
  WarmLights = 38,
  EvilPresences,
  TreasureChests,
  Rooms,
  WarmLightEffectiveness,
  MonsterDifficulty,
  ExperienceGained,
  ItemDrops,
  ItemQuality,
  Swarm,
  GuildPoints,
  LevelUp,
  LevelCap,
}

const statNames: Record<Stats, string> = {
  [CharacterStats.EnhancedEffect]: "% Enhanced Effect",
  [CharacterStats.Strength]: "Strength",
  [CharacterStats.Dexterity]: "Dexterity",
  [CharacterStats.Vitality]: "Vitality",
  [CharacterStats.Intelligence]: "Intelligence",
  [CharacterStats.MaxLife]: "Max Life",
  [CharacterStats.MaxMana]: "Max Mana",
  [CharacterStats.ExperienceGained]: "% Experience Gained",
  [CharacterStats.MagicLuck]: "Magic Luck",
  [CharacterStats.LifeRegen]: "Life Regen",
  [CharacterStats.ManaRegen]: "Mana Regen",
  [CharacterStats.ExtraEquipmentSlots]: "Extra Equipment Slots",
  [CharacterStats.CriticalStrike]: "Critical Strike",
  [CharacterStats.LifePerAttack]: "Life PerAttack",
  [CharacterStats.ManaPerAttack]: "Mana Per Attack",
  [CharacterStats.LifePerKill]: "Life Per Kill",
  [CharacterStats.ManaPerKill]: "Mana Per Kill",
  [CharacterStats.LifeSteal]: "% Life Steal",
  [CharacterStats.DamageReturn]: "% Damage Return",
  [CharacterStats.MindNumb]: "% Mind Numb",
  [CharacterStats.ArmorPierce]: "% Armor Pierce",
  [CharacterStats.Parry]: "% Parry",
  [CharacterStats.CriticalFlux]: "% Critical Flux",
  [CharacterStats.PhysicalDamageReduction]: "% Physical Damage Reduction",
  [CharacterStats.MagicalDamageReduction]: "% Magical Damage Reduction",
  [CharacterStats.ManaSyphon]: "% Mana Syphon",
  [CharacterStats.QuickDraw]: "% Quick Draw",
  [CharacterStats.ManaConsumption]: "% Mana Consumption",
  [CharacterStats.IceMastery]: "% Ice Mastery",
  [CharacterStats.FireMastery]: "% Fire Mastery",
  [CharacterStats.LightningMastery]: "% Lightning Mastery",
  [CharacterStats.EarthMastery]: "% Earth Mastery",
  [CharacterStats.WindMastery]: "% Wind Mastery",
  [CharacterStats.HealMastery]: "% Heal Mastery",
  [CharacterStats.ManaSkin]: "% Mana Skin",
  [CharacterStats.PowerShot]: "% Power Shot",
  [CharacterStats.GlancingBlow]: "% Glancing Blow",
  [CharacterStats.Jubilance]: "Jubilance",
  [ItemStats.WarmLights]: "Warm Lights",
  [ItemStats.EvilPresences]: "Evil Presences",
  [ItemStats.TreasureChests]: "Treasure Chests",
  [ItemStats.Rooms]: "Rooms",
  [ItemStats.WarmLightEffectiveness]: "% Warm Light Effectiveness",
  [ItemStats.MonsterDifficulty]: "% Monster Difficulty",
  [ItemStats.ExperienceGained]: "% Experience Gained",
  [ItemStats.ItemDrops]: "% Item Drops",
  [ItemStats.ItemQuality]: "% Item Quality",
  [ItemStats.Swarm]: "% Swarm",
  [ItemStats.GuildPoints]: "% Guild Points",
  [ItemStats.LevelUp]: "% Level Up",
  [ItemStats.LevelCap]: "Level Cap"
}


const itemSpecificStatNames: Record<Stats, string> = {
  ...statNames,
  [CharacterStats.MaxLife]: "Heals {x} Life",
  [CharacterStats.MaxMana]: "Recovers {x} Mana",
  [CharacterStats.ExperienceGained]: "% Cooked"
}


export { statNames, itemSpecificStatNames }
export type Stats = CharacterStats | ItemStats;