export enum CharacterStats {
  EnhancedEffect,
  Strength,
  Dexterity,
  Vitality,
  Intelligence,
  MaxLife,
  MaxMana,
  ExperienceGained,
  MagicLuck,
  LifeRegen,
  ManaRegen,
  ExtraEquipmentSlots,
  CriticalStrike,
  LifePerAttack,
  ManaPerAttack,
  LifePerKill,
  ManaPerKill,
  LifeSteal,
  DamageReturn,
  MindNumb,
  ArmorPierce,
  Parry,
  CriticalFlux,
  PhysicalDamageReduction,
  MagicalDamageReduction,
  ManaSyphon,
  QuickDraw,
  ManaConsumption,
  IceMastery,
  FireMastery,
  LightningMastery,
  EarthMastery,
  WindMastery,
  HealMastery,
  ManaSkin,
  PowerShot,
  GlancingBlow,
  Jubilance,
}


export enum ItemStats {
  WarmLights = 38,
  EvilPresences,
  TreasureChests,
  Rooms,
  WarmLightEffectiveness,
  MonsterDifficulty,
  ExperienceGained,
  ItemDrops,
  ItemQuality,
  Swarm,
  GuildPoints,
  LevelUp,
  LevelCap,
}

export type Stats = CharacterStats | ItemStats;