enum RequestPacketType {
  Ping,
  Pong,
  ListCharacters,
  CreateCharacter,
  SendChatMessage,
  SelectCharacter,
  CreateGroup,
  ListGroups,
  JoinGroup,
  LeaveGroup,
  GetUser,
  SetGroupLeader,
  UpdateCharacter,
  EquipItem,
  UnequipItem,
  DeleteItem,
  UpdateMaze,
  MoveDirection,
  AttackTarget,
  ChangeZone,
  PickGroundItem,
  ShrineItem,
  StartSkill,
  DoSkillAction,
  StopSkill,
  StackItem,
  UseItem,
}

export default RequestPacketType;